network: ${NETWORK}
apps:
  publicApi:
    port: ${PUBLIC_API_PORT}
    prefix: ${PUBLIC_API_PREFIX}
  privateApi:
    port: ${PRIVATE_API_PORT}
urls:
  api: ${API_URL}
  redis: ${REDIS_URL}
  elastic: ${ELASTIC_URL}
keepAlive:
  enable: true
  downstreamTimeout: 61000
  upstreamTimeout: 60000
caching:
  poolLimit: 100
  processTtl: 60
xExchange:
  shardId: 1
