network: ${NETWORK}
apps:
  publicApi:
    port: ${PUBLIC_API_PORT}
    prefix: ${PUBLIC_API_PREFIX}
  privateApi:
    port: ${PRIVATE_API_PORT}
  cacheWarmer:
    port: ${CACHE_WARMER_PORT}
urls:
  api: ${API_URL}
  redis: ${REDIS_URL}
  elastic: ${ELASTIC_URL}
keepAlive:
  enable: true
  downstreamTimeout: 61000
  upstreamTimeout: 60000
caching:
  poolLimit: 100
  processTtl: 60
xExchange:
  routerAddress: 'erd1qqqqqqqqqqqqqpgqq66xk9gfr4esuhem3jru86wg5hvp33a62jps2fy57p'
tokens:
  WEGLD: 'WEGLD-bd4d79'
  WUSDC: 'USDC-c76f1f'
